# Site-wide settings
title: Aging Health
author:
  name: Tommy T. Douglas
  email: # Add your email here if desired

description: >-
  Educational resources, clinical briefings, and insights on geriatric longevity and metabolic health.

# Build settings
remote_theme: jekyll/minima@v2.5.1
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

# Minima-specific settings
minima:
  skin: auto
  show_excerpts: true
  date_format: "%b-%d-%Y"
  nav_pages:
    - about.md
  
  # Hide social links for now or customize as needed
  hide_site_feed_link: false

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge